server:
  port: 8681  
  
spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:8889
  sleuth:
    sampler:
      percentage: 1.0
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/    #注册 中心已经开启认证
      
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service